/**
 * The <head> snippet that makes a WORKER-served standalone page (e.g. /superadmin, /cockpit) obey the site theme:
 * link the shared color-scheme sheet (/schemes.css — base light/dark + every scheme, generated by gen-schemes.ts)
 * and a no-flash stamper that applies the visitor's saved theme + scheme onto <html> before first paint. No
 * @suluk/theme import here, so it adds nothing to the worker bundle beyond a string.
 */
export const THEME_STAMPER =
  "(function(){try{var d=document.documentElement;var t=localStorage.getItem('theme');" +
  "if(!t)t=(window.matchMedia&&matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light';" +
  "d.dataset.theme=t;var s=localStorage.getItem('scheme');if(s)d.dataset.scheme=s;}catch(e){}})();";

/** Inject into a standalone page's <head> (after any default theme) so it follows the site's theme + scheme. */
export function themeHeadHtml(): string {
  return `<script>${THEME_STAMPER}</script><link rel="stylesheet" href="/schemes.css"/>`;
}
