-- generated by scripts/sync-catalog.ts — apply to D1.
UPDATE product SET stripe_price_id='price_1Tgvn4R9OvhT1CxIqZkqI5PL' WHERE slug='frontend-lite';
UPDATE product SET stripe_price_id='price_1Tgvn4R9OvhT1CxIpWoBv2Dc' WHERE slug='frontend-pro';
UPDATE product SET stripe_price_id='price_1Tgvn5R9OvhT1CxIZLMuLmMG' WHERE slug='fullstack-lite';
UPDATE product SET stripe_price_id='price_1Tgvn5R9OvhT1CxIPIO0GdfO' WHERE slug='fullstack-pro';
UPDATE product SET stripe_price_id='price_1Tgvn6R9OvhT1CxIgOpUfabq' WHERE slug='ecommerce-module';
UPDATE product SET stripe_price_id='price_1Tgvn6R9OvhT1CxIlcpTc9B6' WHERE slug='auth-module';
UPDATE product SET stripe_price_id='price_1Tgvn7R9OvhT1CxIh9MbXBk4' WHERE slug='cost-ledger';
UPDATE product SET stripe_price_id='price_1Tgvn7R9OvhT1CxIO6n2qag3' WHERE slug='admin-cockpit';
UPDATE product SET stripe_price_id='price_1Tgvn8R9OvhT1CxIUnM6hNqx' WHERE slug='stripe-billing';
