/**
 * Generate public/schemes.css — the BASE light/dark theme + all 43 tweakcn `[data-scheme]` blocks — so the
 * worker-served standalone pages (/superadmin, /cockpit) share the EXACT same color schemes as the site (which
 * inlines the same projection at build). Run before `astro build` (see package.json `build`). The base block
 * mirrors Layout.astro's default indigo theme so the unset scheme matches the site.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { projectScheme } from "../src/themes/project";

const root = fileURLToPath(new URL("..", import.meta.url));

// Deploy id for @suluk/seo skew-protection — the committed git SHA (else a timestamp). Written to src/build-id.ts,
// consumed by the Layout (<meta> + guard) and the worker (/api/health header). Runs before both builds.
let buildId = "dev";
try {
  buildId = execSync("git rev-parse --short HEAD", { cwd: root }).toString().trim() || "dev";
} catch {
  buildId = String(Date.now());
}
writeFileSync(
  join(root, "src/build-id.ts"),
  `/** Generated by scripts/gen-schemes.ts — the deploy id for @suluk/seo skew-protection. */\nexport const BUILD_ID = ${JSON.stringify(buildId)};\n`,
);
console.log(`wrote src/build-id.ts — ${buildId}`);
const dir = join(root, "src/themes/schemes");

const BASE = `:root,html[data-theme="light"]{color-scheme:light;--bg:#ffffff;--bg-soft:#f7f7fb;--panel:#ffffff;--line:#ececf1;--fg:#0b0b12;--muted:#646474;--accent:#6366f1;--accent-2:#8b5cf6;--link:#4f46e5;--on-accent:#ffffff;--shadow:0 1px 2px rgba(16,16,40,.06),0 12px 34px rgba(16,16,40,.10)}
html[data-theme="dark"]{color-scheme:dark;--bg:#09090c;--bg-soft:#0d0d12;--panel:#131319;--line:#23232c;--fg:#ededf2;--muted:#8c8c99;--accent:#818cf8;--accent-2:#a78bfa;--link:#a5b4fc;--on-accent:#0b0b12}`;

const blocks = readdirSync(dir)
  .filter((f) => f.endsWith(".css"))
  .sort()
  .map((f) => projectScheme(f.replace(/\.css$/, ""), readFileSync(join(dir, f), "utf8")))
  .filter(Boolean);

const out = `/* GENERATED by scripts/gen-schemes.ts — base theme + ${blocks.length} tweakcn color schemes, shared by the site, /superadmin and /cockpit. Do not edit. */\n${BASE}\n${blocks.join("\n")}\n`;
mkdirSync(join(root, "public"), { recursive: true });
writeFileSync(join(root, "public/schemes.css"), out);
console.log(`wrote public/schemes.css — base + ${blocks.length} schemes (${(out.length / 1024).toFixed(0)}KB)`);
