/**
 * gen-icons — extract ONLY the icons named in src/icons.ts `ICON` into a tiny, client-safe data module
 * (src/lib/icon-data.ts). Run via `bun run gen:icons` (wired into the build, like gen:schemes).
 *
 * Why: astro-icon's <Icon> is build-time + .astro-only, so it can't be used inside the React chrome islands
 * (ThemeToggle, CartButton, …). Rather than ship lucide OR bundle a whole Iconify set to the client, we pre-extract
 * just the handful of <svg> bodies actually referenced — from the SAME local @iconify-json sets astro-icon uses
 * (material-symbols + line-md + devicon). The client bundles zero icon libraries and makes no CDN call; the React
 * <Icon> (src/components/ui/icon.tsx) just injects a body string. One registry (src/icons.ts) still drives both paths.
 */
import { getIconData, iconToSVG } from "@iconify/utils";
import { icons as materialSymbols } from "@iconify-json/material-symbols";
import { icons as lineMd } from "@iconify-json/line-md";
import { icons as devicon } from "@iconify-json/devicon";
import { ICON } from "../src/icons.ts";

const SETS: Record<string, typeof materialSymbols> = {
  "material-symbols": materialSymbols,
  "line-md": lineMd,
  devicon,
};

// devicon brand logos are full-color and only ever rendered server-side in .astro via astro-icon's <Icon> (the
// showcase "Built on" strip) — never inside a React island — so we keep them OUT of the client data map to avoid
// shipping ~15KB of gradient paths to every page's chrome bundle. They still live in src/icons.ts for the .astro side.
const names = [...new Set(Object.values(ICON))].filter((n) => !n.startsWith("devicon:")).sort();
const missing: string[] = [];
const entries = names
  .map((full) => {
    const [prefix, ...rest] = full.split(":");
    const data = SETS[prefix] && getIconData(SETS[prefix], rest.join(":"));
    if (!data) {
      missing.push(full);
      return null;
    }
    // height:"1em" yields a viewBox + currentColor/stroke body verbatim (iconToHTML's pipeline). We keep the raw ids
    // (devicon gradients) — the React <Icon> uniquifies them per-instance so repeated logos don't collide.
    const built = iconToSVG(data, { height: "1em" });
    return { full, body: built.body, viewBox: built.attributes.viewBox };
  })
  .filter(Boolean) as { full: string; body: string; viewBox: string }[];

if (missing.length) {
  console.error("✗ gen-icons: unknown icon name(s) — fix src/icons.ts:\n  " + missing.join("\n  "));
  process.exit(1);
}

const rows = entries
  .map((e) => `  ${JSON.stringify(e.full)}: { viewBox: ${JSON.stringify(e.viewBox)}, body: ${JSON.stringify(e.body)} },`)
  .join("\n");

const out = `/* eslint-disable */
/**
 * GENERATED by scripts/gen-icons.ts — do NOT edit by hand. Run \`bun run gen:icons\`.
 * Only the icons named in src/icons.ts ICON are inlined (one <svg> body each), so the React chrome renders
 * Iconify icons with no icon library and no network. Sets: @iconify-json/material-symbols + line-md + devicon.
 */
export const ICON_DATA: Record<string, { viewBox: string; body: string }> = {
${rows}
};
`;

await Bun.write("src/lib/icon-data.ts", out);
console.log(`✓ gen-icons: wrote src/lib/icon-data.ts — ${entries.length} icons`);
