// Computes a short content hash of the vendored forked-Scalar bundle and writes it to
// worker/gen/scalar-fork.ts. The worker appends it as a `?v=` query on /reference's <script src>,
// so browsers cache-bust the moment the fork is rebuilt — we pull upstream + reapply the patch-set
// regularly (the bundle changes often), and the fixed filename would otherwise serve a stale Scalar.
const bundle = "public/vendor/scalar/standalone-suluk.js";
const out = "worker/gen/scalar-fork.ts";

// Marker baked in by scalar-fork/patches/0001 — its presence proves the served bytes are OUR patched fork, not
// stock upstream Scalar (which would silently drop every v4 superpower at /reference).
const PATCH_MARKER = "Suluk OpenAPI v4 contract";

const file = Bun.file(bundle);
if (!(await file.exists())) {
  // The fork bundle is committed (see .gitignore), so a missing file means a broken tree/checkout — fail loudly
  // rather than emitting a "dev" hash and shipping a /reference that 404s its <script> (audit #1).
  console.error(`scalar-fork: FATAL — ${bundle} is missing. The forked Scalar bundle is committed; restore it`);
  console.error(`  (git checkout -- ${bundle}) or rebuild it (tooling/ts/scalar-fork/build.sh). Refusing to build.`);
  process.exit(1);
}
const text = await file.text();
if (!text.includes(PATCH_MARKER)) {
  // Bundle exists but is stock/unpatched upstream — /reference would render with all v4 superpowers missing (audit #4).
  console.error(`scalar-fork: FATAL — ${bundle} is present but UNPATCHED (no "${PATCH_MARKER}" marker).`);
  console.error(`  Rebuild the fork (tooling/ts/scalar-fork/build.sh) so the suluk v4 patches are baked in.`);
  process.exit(1);
}
const hash = Bun.hash(text).toString(16);
await Bun.write(out, `// AUTO-GENERATED by scripts/scalar-fork-hash.ts — do not edit.\nexport const SCALAR_FORK_HASH = ${JSON.stringify(hash)};\n`);
console.log(`scalar-fork: ${bundle} (patched ✓) → ?v=${hash}`);
