// Computes a short content hash of the vendored forked-Scalar bundle and writes it to
// worker/gen/scalar-fork.ts. The worker appends it as a `?v=` query on /reference's <script src>,
// so browsers cache-bust the moment the fork is rebuilt — we pull upstream + reapply the patch-set
// regularly (the bundle changes often), and the fixed filename would otherwise serve a stale Scalar.
const bundle = "public/vendor/scalar/standalone-suluk.js";
const out = "worker/gen/scalar-fork.ts";

const file = Bun.file(bundle);
if (!(await file.exists())) {
  // Fork bundle not vendored yet (fresh checkout) — emit a stable placeholder so imports resolve.
  await Bun.write(out, `// AUTO-GENERATED by scripts/scalar-fork-hash.ts — do not edit.\nexport const SCALAR_FORK_HASH = "dev";\n`);
  console.log(`scalar-fork: ${bundle} missing → ?v=dev`);
} else {
  const hash = Bun.hash(await file.arrayBuffer()).toString(16);
  await Bun.write(out, `// AUTO-GENERATED by scripts/scalar-fork-hash.ts — do not edit.\nexport const SCALAR_FORK_HASH = ${JSON.stringify(hash)};\n`);
  console.log(`scalar-fork: ${bundle} → ?v=${hash}`);
}
