/**
 * One-time: create a real Stripe Product + one-time Price for each seeded, paid, published product, and emit
 * the SQL to point each product row at its Stripe Price. Run: `bun run scripts/sync-catalog.ts`, then apply the
 * printed scripts/catalog.sql to the dbs (dev re-seeds in-memory; for prod: wrangler d1 execute ... catalog.sql).
 * Idempotent-ish: re-running creates new prices — run once, or clear stripe_price_id first.
 */
import { writeFileSync } from "node:fs";
import { restStripe } from "../src/server/stripe-rest";
import { SEED_PRODUCTS } from "../src/server/seed";

const key = process.env.STRIPE_SECRET_KEY;
if (!key) {
  console.error("set STRIPE_SECRET_KEY in .env");
  process.exit(1);
}
const stripe = restStripe(key);

// IDEMPOTENT: skip products that already carry a Stripe price in the live catalog (set FORCE=1 to recreate).
const base = process.env.CATALOG_BASE ?? "https://saasuluk.saastemly.com";
const live = (await fetch(`${base}/product`)
  .then((r) => r.json())
  .catch(() => [])) as { slug: string; stripePriceId?: string }[];
const alreadyPriced = new Set(live.filter((p) => p.stripePriceId).map((p) => p.slug));

const updates: string[] = [];
for (const p of SEED_PRODUCTS) {
  if (p.status !== "published" || p.priceCents <= 0) continue; // free / draft products aren't sold via Stripe
  if (alreadyPriced.has(p.slug) && process.env.FORCE !== "1") {
    console.log(`  ${p.slug.padEnd(20)} → already priced (skip; FORCE=1 to recreate)`);
    continue;
  }
  const product = await stripe.products.create({ name: p.name, description: p.description, metadata: { slug: p.slug } } as Record<
    string,
    unknown
  >);
  // a one-time Price (no `recurring`) in cents — the adapter form-encodes the params
  const price = await stripe.prices.create({ product: (product as { id: string }).id, currency: "usd", unit_amount: p.priceCents });
  const priceId = (price as { id: string }).id;
  console.log(`  ${p.slug.padEnd(20)} → ${priceId}`);
  updates.push(`UPDATE product SET stripe_price_id='${priceId}' WHERE slug='${p.slug}';`);
}

writeFileSync("scripts/catalog.sql", "-- generated by scripts/sync-catalog.ts — apply to D1.\n" + updates.join("\n") + "\n");
console.log(`\n✓ ${updates.length} Stripe prices created → scripts/catalog.sql`);
console.log("→ apply to the live DB: wrangler d1 execute saasuluk-db --file=./scripts/catalog.sql --remote\n");
